// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCEKD2dmUfoyseG_6N-d_nrFh3Ufc-KhTU',
    appId: '1:584886105529:web:3796160210412e593d3268',
    messagingSenderId: '584886105529',
    projectId: 'hostelkube',
    authDomain: 'hostelkube.firebaseapp.com',
    databaseURL: 'https://hostelkube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostelkube.appspot.com',
    measurementId: 'G-VEM78RKGFD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4fP5k5adaDOsafGRGQlWB8warhxvfavY',
    appId: '1:584886105529:android:b1f9ce51f5e17c2c3d3268',
    messagingSenderId: '584886105529',
    projectId: 'hostelkube',
    databaseURL: 'https://hostelkube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostelkube.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB81LVY2q3WdlQs1p5X9ApbBWMv-4_hLOI',
    appId: '1:584886105529:ios:080aea251612cb863d3268',
    messagingSenderId: '584886105529',
    projectId: 'hostelkube',
    databaseURL: 'https://hostelkube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostelkube.appspot.com',
    iosBundleId: 'com.example.hostelkubeFrontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB81LVY2q3WdlQs1p5X9ApbBWMv-4_hLOI',
    appId: '1:584886105529:ios:080aea251612cb863d3268',
    messagingSenderId: '584886105529',
    projectId: 'hostelkube',
    databaseURL: 'https://hostelkube-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'hostelkube.appspot.com',
    iosBundleId: 'com.example.hostelkubeFrontend',
  );
}
