name: hostelkube_frontend
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  carousel_slider: ^4.0.0
  flutter_native_splash: ^2.2.18
  google_fonts: ^4.0.4
  http: ^0.13.3
  fluttertoast: ^8.2.2
  firebase_core: ^2.17.0
  firebase_auth: ^4.10.1
  cloud_firestore: ^4.9.3
  razorpay_flutter: ^1.3.5
  firebase_database: ^10.2.7
  shared_preferences: ^2.2.1
  pdf: any
  path_provider: any
  open_file: any
  razorpay_web: ^1.4.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/Ellipse12.png
    - assets/Image2.png
    - assets/Image3.png
    - assets/Image4.png
    - assets/Image5.png
    - assets/Image7.png
    - assets/Image10.png
    - assets/Image12.png
    - assets/rectangle2.svg
    - assets/rectangle3.svg
    - assets/Rectangle5.png
    - assets/rectangle10.svg
    - assets/pexels-cottonbro-studio-5137969.jpg
    - assets/pexels-pixabay-50987.jpg
    - assets/pexels-spencer-davis-4393021.jpg
    - assets/Image1.png
    - assets/Image6.png
    - assets/signin/signin_balls.png
    - assets/background.png
    - assets/name.png

  # fonts:
    # Add your custom fonts if needed


